name: eventstr
description: "Nostr event store"
version: 0.0.3
repository: https://github.com/1l0/eventstore-flutter/tree/master/packages/eventstr

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  fixnum: ^1.1.0
  flutter:
    sdk: flutter
  nip01: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
