name: eventstore
description: "Nostr event store"
version: 0.0.3
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  fixnum: ^1.1.0
  flutter:
    sdk: flutter
  nip01: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
