name: eventstore_sqflite
description: "Nostr event store with sqflite"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  fixnum: ^1.1.0
  flutter:
    sdk: flutter
  nip01:
    git:
      url: https://github.com/kumulynja/dartstr.git
      path: packages/nip01
      version: ^0.0.1
  eventstore:
    git:
      url: https://github.com/1l0/eventstore-flutter.git
      path: packages/eventstore
      ref: 9b5e54cea7f9cd8eb9aed37abc9a0d4159e7bebf
  sqflite_common_ffi: ^2.3.3+1
  sqflite_common_ffi_web: ^0.4.5+3
  sqflite_common: ^2.5.4+4
  sqflite: ^2.3.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
